# Generated by Django 4.2.1 on 2023-06-13 15:57

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_institution_teacher_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.institution'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
