# Generated by Django 4.2.1 on 2023-06-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_student_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_data_completed',
            field=models.BooleanField(default=False),
        ),
    ]
