# Generated by Django 4.2.1 on 2023-06-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_teacher_birth_date_alter_teacher_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.institution'),
        ),
    ]
