# Generated by Django 4.2.1 on 2023-06-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_student_institution_alter_teacher_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
